import React from 'react'
import Link from 'next/link'
import Navbar from '../components/Navbar';
import RegisterPage from '../components/Register'
import Data from '../../pages/api/User/data.json'
import Image from 'next/image';
import Head from 'next/head';

const Register = () => {
    return (
        <div>
          <Head>
            <title>PERAK 2022</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/img/favicon.ico" />
            <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Roboto&display=swap" rel="stylesheet">
            </link>
          </Head>
          <Navbar/>
          <main className="w-full h-full bg-bg-styles bg-fixed">
            <div className="flex px-20 py-5">
              <Image
                  src="/img/Registered-Title-1.png"
                  alt="Registered-Title-1"
                  width={600}
                  height={40}   
              />
            </div>
            <div className='flex px-10'>
            <RegisterPage/>
            </div>
          </main>
        </div>
      );
    };

export default Register
