import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Navbar from "./components/Navbar";
import React from "react";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className=" w-full h-full bg-bg-styles bg-cover">
      <Head>
        <title>PERAK 2022</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800;900&family=Roboto&display=swap" rel="stylesheet">
        </link>
      </Head>
      <Navbar/>
      <main className="">
        <div className="flex px-20 py-5">
          <Image
              src="/img/Home-Title-1.png"
              alt="Home-Title-1"
              width={300}
              height={75}   
          />
        </div>
        <div className="flex px-20 py-3">
          <Image
            src="/img/Home-Title-2.png"
            alt="Home-Title-2"
            width={170}
            height={20}   
          />
        </div>
        <div className="flex px-20">
          <Link href="/Register">
            <Image
                src="/img/brawlhalla.png"
                alt="brawlhalla"
                width={157}
                height={123}   
            />
          </Link>
        <div className="lg: px-5 py-0">
          <Link href="/Register">
            <Image
                src="/img/osu.png"
                alt="osu"
                width={157}
                height={123}   
              />
          </Link>
        </div>
          <Link href="/Register">
            <Image
              src="/img/chess.png"
              alt="chess"
              width={157}
              height={123}   
            />
          </Link>
        </div>
      </main>
      <div className="bg-left-bottom py-20">
        <Image
            src="/img/cloud-1.png"
            alt="cloud-1"
            width={200}
            height={123}   
        />
        <Image
            src="/img/cloud-1.png"
            alt="cloud-1"
            width={200}
            height={123}   
        />
        <Image
            src="/img/cloud-1.png"
            alt="cloud-1"
            width={200}
            height={123}   
        />
        <Image
            src="/img/cloud-1.png"
            alt="cloud-1"
            width={200}
            height={123}   
        />
        <Image
            src="/img/cloud-1.png"
            alt="cloud-1"
            width={200}
            height={123}   
        />
        </div>
    </div>
  );
};

export default Home